### ISSUE TITLE
Reproducibility

### ISSUE THREAD

**Issue by faroit** [jordipons/ICASSP2017#1]
👍  for sharing your code.

For the sake of reproducibility I suggest you add the exact python package environments in a `requirements.txt`

Also do not push dependency code as part of the repo (lasagne) but rather add it as a requirement (including the exact version). And if you made changes to lasagne you can also fork it and add your fork as a requirement

**Comment by faroit** [comment]
oh and maybe this affects this repo as well https://github.com/jordipons/EUSIPCO2017

**Comment by jordipons** [comment]
Thanks for the feedback!

I know these issues/limitations - but some colleagues had problems running this code when using the infrastructure you are suggesting. Finally, we decided that this was the fastest (but less elegant) way of sharing the code! For these reasons, we are now changing our implementation backend - and (hopefully) the code for future papers will be easier to share.

**Comment by faroit** [comment]
I don't understand what you mean by 

>  but some colleagues had problems running this code when using the infrastructure you are suggesting

The requirements file includes all the dependencies and possibly their versions. Users don't have to install these, they can go for whatever version they like to. But 

1. not stating the exact version can make it almost impossible to reproduce the results
2. Including code from other repositories makes it hard to track changes
